JonatanS/demography

- server/db/models/chart.js
- server/db/models/index.js
set up chart model w/ ref to dashboard
> Closes #18

- browser/js/fsa/fsa-pre-built.js
- browser/js/login/login.html
- browser/js/signup/signup.js
- server/db/models/user.js
add local signup functionality
> closes #19

- browser/js/common/directives/navbar/navbar.js
- browser/js/profile/profile.html
- browser/js/profile/profile.js
- server/db/models/user.js
created profile state and button
> Closes #21

- server/app/routes/dashboards/index.js
- server/app/routes/index.js
> Closes #33

- browser/js/common/directives/load-file/load-file.html
- browser/js/common/factories/profile.factory.js
- browser/js/profile/profile.js
- server/app/routes/users/index.js
- server/db/models/dataSet.js
Implement user and project id file saving system
> closes #42

- server/app/routes/datasets/index.js
- server/app/routes/users/index.js
> closes #50

- server/app/routes/dashboards/index.js
Updated according to group consensus, also es6ified
> Closes #51

- browser/js/about/about.html
- browser/js/about/about.js
- browser/scss/directives/_main.scss
- browser/scss/directives/fullstack-logo.scss
- browser/scss/main.scss
- server/app/routes/index.js
Fix bugs introduced when stripping out fsg stuff
> closes #67

- server/app/routes/datasets/index.js
- server/app/routes/users/index.js
Added proper error handling / status codes on all routes
> Closes #55

- browser/js/common/directives/navbar/navbar.html
- browser/js/common/directives/navbar/navbar.js
- browser/js/docs/docs.html
- browser/js/repository/repository.html
- browser/js/repository/repository.js
- browser/scss/directives/navbar.scss
- server/app/views/index.html
Update navbar for content and some initial styling
> closes #69

- browser/scss/dashboard/widget.scss
Fix modal spacing so it doesn't overlap with nabar
> closes #75

- browser/js/common/factories/profile.factory.js
- browser/js/profile/profile.html
- browser/js/profile/profile.js
- browser/js/stream/stream.html
- server/app/routes/datasets/index.js
successfully displaying datasets on profile
> closes #97

- browser/js/common/directives/navbar/navbar.html
- browser/scss/directives/navbar.scss
- browser/scss/variables.scss
Removed placeholder formatting from navbar so we can start with the clean Bootstrap theme, and then tailor the design from there
> closes #113

- browser/js/common/factories/dataset.factory.js
- browser/js/profile/profile.html
- browser/js/profile/profile.js
Add placeholder delete dataset button to profile page
> closes #116

- browser/js/common/factories/dashboard.factory.js
- browser/js/common/factories/dataset.factory.js
- browser/js/profile/profile.html
- browser/js/profile/profile.js
- server/app/routes/dashboards/index.js
- server/app/routes/datasets/index.js
- server/db/upload-files/user:56ae49cf3a046d61a3148320-dataset:56afc1565a67a6d8ecdb8166.csv
- server/db/upload-files/user:56ae5941c2a52e85b1498e55-dataset:56afd0c989b1ef23ed90c53c.csv
Added a placeholder delete dashboards button so we can remove test dashboards from the UI
> closes #121

- browser/js/profile/profile.html
> closes #134

- browser/js/common/services/graph.service.js
- browser/js/widget/widget.settings.controller.js
Implemented support for line charts
> Closes #133

- browser/js/stream/stream.html
- server/db/models/dashboard.js
Stream search bar successfully filters according to dashboard name or tags
> Closes #138

- browser/js/common/factories/user.factory.js
- browser/js/user/user.dashboards.html
- browser/js/user/user.datasets.html
- browser/js/user/user.html
- browser/js/user/user.js
Data is being populated on User state (state for viewing other users data,dashboards,and info).  Only the data is showing, there isn't any html being rendered.  Also need to sanitize the user information and the user datasets.
> Closes #158

- server/app/routes/users/index.js
- server/db/models/user.js
User information is now sanitized using a method on the User model.  Prevents email and google ID from being sent.
> Closes #160

- browser/js/common/directives/navbar/navbar.html
- browser/js/common/directives/navbar/navbar.js
- browser/js/dashboard/dashboard.edit.html
- browser/scss/dashboard/dashboard.scss
- browser/scss/directives/navbar.scss
- browser/scss/variables.scss
Update navbar format so its inline with Yeti bootstrap theme
> closes #119

- browser/js/profile/profile-datasets.settings.controller.js
- browser/js/profile/profile.js
Auto redirect to datasets after uploading a new one
> closes #188

- browser/js/profile/profile-dashboards.html
- browser/scss/profile/profile-dashboards.scss
profile.dashboards looking good
> Closes #169

- browser/js/profile/profile.js
- server/app/views/index.html
Remove dashboards from $scope.array when associated dataset is deleted
> closes #192

- package.json
- server/app/routes/datasets/index.js
Add ability to flatten json files when sending to front end
> closes #205

- browser/js/common/directives/widget/widget.js
- browser/js/common/factories/widget.factory.js
- browser/js/common/services/graph.service.js
- browser/js/widget/widget.controller.js
- browser/js/widget/widget.settings.controller.js
- browser/js/widget/widget.settings.html
- browser/scss/dashboard/dashboard.scss
- browser/scss/dashboard/widget.scss
Tied ui in front end that allows users to pick graph grouping to the functionality in the backend.  Also stores the grouping info on the widget so it will populate correctly.
> Closes #207

- browser/js/common/directives/widget/widget.html
- browser/js/common/directives/widget/widget.js
- browser/js/common/services/graph.service.js
- browser/scss/dashboard/widget.scss
Fix chart labels so they don't overlap data. Need to improve it further to make it dynamic
> closes #198

- browser/js/profile/profile.js
- server/app/routes/dashboards/index.js
- server/app/routes/datasets/index.js
- server/app/routes/route-utilities.js
Move helper functions out of datasets routes into utilities file
> closes #225

- browser/js/profile/profile-dashboards.html
- browser/js/profile/profile-datasets.html
- browser/js/profile/profile.html
- browser/scss/profile/profile-dashboards.scss
- browser/scss/profile/profile-datasets.scss
> closes #227

- Find Results
- server/app/configure/authentication/local.js
- server/app/routes/dashboards/index.js
- server/app/routes/datasets/index.js
- tests/server/models/user-test.js
- tests/server/routes/dashboards-test.js
- tests/server/routes/datasets-test.js
Tests in place for both Dashboard and Dataset routes.  Currently failing some tests as routes need to be fixed.
> Closes #125

- browser/js/common/factories/dataset.factory.js
- browser/js/profile/profile.js
> closes #234

- browser/scss/profile/profile-dashboards.scss
Profile dashboards no longer overflowing
> Closes #238

- browser/js/widget/widget.settings.controller.js
- browser/js/widget/widget.settings.html
- browser/scss/dashboard/widget.scss
Top part of modal (above accordion) in place
> Closes #243

- browser/js/common/directives/widget/widget.js
- browser/js/common/services/chart.service.js
- browser/scss/dashboard/widget.scss
> Resizing is working

- browser/js/common/services/chartUtils.service.js
added support for y tick margins
> Closes #253

- bower.json
- browser/js/profile/profile-datasets.html
- browser/js/profile/profile-datasets.settings.controller.js
- browser/js/profile/profile-datasets.settings.html
- browser/js/profile/profile.js
- browser/scss/profile/profile-datasets.scss
Add edit button to profile datasets
> closes #267

- browser/js/common/factories/dashboard.factory.js
- browser/js/dashboard/dashboard.js
- browser/js/profile/profile.js
- server/app/routes/screenshots/index.js
No more problems w/ screenshots
> Closes #261

- browser/js/common/directives/create-barchart/create-barchart.js
- browser/js/common/directives/create-datatable/create-datatable.js
- browser/js/common/directives/create-linechart/create-linechart.js
- browser/js/common/directives/create-piechart/create-piechart.js
- browser/js/common/directives/create-rowchart/create-rowchart.js
- browser/js/widget/widget.settings.controller.js
> closes #277

- browser/js/common/factories/dashboard.factory.js
- browser/js/common/factories/dataset.factory.js
- browser/js/dashboard/dashboard.js
- browser/js/profile/profile-dashboards.html
- browser/js/profile/profile-dashboards.settings.controller.js
- browser/js/profile/profile.js
- browser/js/stream/stream.html
- browser/js/stream/stream.js
- package.json
- server/app/routes/dashboards/index.js
- server/app/routes/datasets/index.js
- server/db/models/dashboard.js
- server/db/models/dataSet.js
Fixed forking datasets. Dorking dashboards needs to be debugged
> closes #37

- browser/js/common/factories/dashboard.factory.js
- browser/js/common/factories/dataset.factory.js
- browser/js/stream/stream.html
- browser/js/stream/stream.js
- server/app/routes/dashboards/index.js
Added ability to fork dashboards, but widgets don't populate
> closes #287

- browser/js/stream/stream.html
- browser/scss/stream/main.scss
> closes #290

- server/env/development.js
Use mongo lab as development database
> closes #301

- README.md
> closes #78

- browser/js/common/services/chart.service.js
- browser/js/dashboard/dashboard.js
- server/app/externalRoutes/index.js
- server/db/models/dataSet.js
Tested it out, seems to work fine. Lemme know if there are probs
- Yus
> Template dashboards
